import React, { useEffect, useState } from 'react';
import { RefreshCw, ShieldCheck, ExternalLink, Search } from 'lucide-react';
import NotConfiguredState from './NotConfiguredState';

export default function CertificateTransparencyPanel() {
  const [data, setData] = useState<any>({ logs: [], certificates: [], totalTrackedCertificates: 0 });
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const r = await fetch('/api/ct-logs'); const v = await r.json(); setData(v); } catch (e) { setError(e instanceof Error ? e.message : 'CT API request failed'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const certs = (data.certificates || []).filter((c: any) => !query || `${c.domain} ${c.issuer} ${(c.san || []).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <div id="section-cert-transparency" className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-200 dark:border-white/5 pb-3"><div><h3 className="text-base font-bold text-gray-900 dark:text-gray-100 flex items-center gap-2"><ShieldCheck className="text-blue-500" size={20}/> Certificate Transparency & Merkle Audit</h3><p className="text-xs text-gray-500">RFC 6962 / RFC 9162 — live CT data only</p></div><div className="flex gap-2"><button onClick={() => void load()} disabled={loading} className="px-3 py-1.5 rounded-xl border text-xs"><RefreshCw size={13} className={loading ? 'animate-spin inline mr-1' : 'inline mr-1'}/>Refresh</button><a href="https://github.com/google/certificate-transparency-go" target="_blank" rel="noreferrer" className="px-3 py-1.5 rounded-xl border text-xs">CT source <ExternalLink size={11} className="inline"/></a></div></div>{error && <div className="text-xs text-rose-500">{error}</div>}{!loading && data.configured === false && <NotConfiguredState feature="Certificate Transparency" reason={data.reason} />}<div className="text-xs text-gray-500">Tracked certificates: <strong>{data.totalTrackedCertificates ?? 0}</strong> · CT logs: <strong>{(data.logs || []).length}</strong></div><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search live certificate records…" className="w-full pl-9 pr-3 py-2 rounded-xl border bg-gray-50 dark:bg-white/5 text-xs"/></div>{certs.length ? <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="p-3">Domain</th><th className="p-3">Issuer</th><th className="p-3">Algorithm</th><th className="p-3">Valid To</th></tr></thead><tbody>{certs.map((c: any) => <tr key={c.id || c.serialNumber} className="border-b last:border-0"><td className="p-3 font-semibold">{c.domain}</td><td className="p-3">{c.issuer || '—'}</td><td className="p-3 font-mono">{c.algorithm || '—'}</td><td className="p-3">{c.validTo || '—'}</td></tr>)}</tbody></table></div> : <div className="rounded-xl border border-dashed p-8 text-center text-xs text-gray-500">No live certificate records returned.</div>}</div>;
}
